//! One-off generator for `crates/core/fuzz/fuzz_targets/rln_verify.rs`'s
//! embedded genuine proof. Run with:
//!
//!     cargo run -p novachannel-rln --release --example gen_fuzz_seed
//!
//! and paste the printed `const` block into the fuzz target. Proving must
//! happen in `--release` (see `lib.rs`'s "Run tests with --release" module
//! doc) — a debug build's extra winterfell sanity check is witness-
//! dependent and can spuriously trip for this AIR's sparse boundary
//! columns. `cargo fuzz build` enables debug-assertions even under its
//! own `--release` profile, which is exactly why the fuzz target embeds a
//! proof generated *here*, once, offline, instead of calling the prover
//! from inside the fuzz binary itself.
use novachannel_rln::air::{self, Witness};
use novachannel_rln::merkle::MerkleTree;
use novachannel_rln::permutation::{compress2, Params};
use novachannel_rln::{bytes_to_field, epoch_field, Identity};
use winterfell::math::fields::f64::BaseElement;
use winterfell::Prover;

fn field_literal(name: &str, v: BaseElement) {
    println!("const {name}: u64 = {};", v.as_int());
}

fn main() {
    let params = Params::new();
    let identity = Identity::generate();
    let leaves = vec![identity.commitment(&params)];
    let tree = MerkleTree::new(air::DEPTH, &leaves);
    let path = tree.path(0);
    let witness = Witness {
        sk: identity.sk,
        path,
    };

    let epoch = epoch_field(1);
    let x = bytes_to_field(b"rln-verify-fuzz-genuine-input");
    let a1 = compress2(&params, identity.sk, epoch);
    let y = identity.sk + a1 * x;

    let trace = air::build_trace(&params, &witness, epoch, x);
    let root = trace.get(0, air::root_row(air::DEPTH));
    let pub_inputs = air::PublicInputs {
        root,
        epoch,
        x,
        y,
        nullifier: a1,
    };

    let prover = air::RlnProver::new(air::default_proof_options(), pub_inputs.clone());
    let proof = prover.prove(trace).expect("proof generation failed");
    let bytes = proof.to_bytes();

    println!("// Generated by `cargo run -p novachannel-rln --release --example gen_fuzz_seed`.");
    field_literal("ROOT", pub_inputs.root);
    field_literal("EPOCH", pub_inputs.epoch);
    field_literal("X", pub_inputs.x);
    field_literal("Y", pub_inputs.y);
    field_literal("NULLIFIER", pub_inputs.nullifier);
    println!("const PROOF_BYTES: &[u8] = &{bytes:?};");
}
